### ISSUE TITLE
BigTable API: CompletableFuture failed with exception

### ISSUE THREAD

**Issue by vankofalcon** [OpenTSDB/asyncbigtable#43]
I was getting this error from time to time when I was doing some highly concurrent writes using the driver. I'm using a single instance of the HBaseClient from many threads that are all doing **AtomicIncrementRequest**. I'm also flushing the client in a timer only from the main thread. In the BigTable dashboard I saw that I was doing like 800 write req/s on a development type instance. 
1) is HBaseClient thread safe?
2) if 1) is yes. I see that the com.google.cloud.bigtable.hbase2_x.FutureUtils class doesn't provide executor when calling toCompletableFuture() method and that might be the issue as well.
What do you guys think is the problem here and how to resolve it?

`ERROR [org.hbase.async.HBaseClient] BigTable API: CompletableFuture failed with exception
java.util.concurrent.CompletionException: io.grpc.StatusRuntimeException: ABORTED: ReadModifyWrite failed: too many concurrent modifications.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.google.cloud.bigtable.hbase2_x.FutureUtils$2.onFailure(FutureUtils.java:51)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1228)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:911)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:822)
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:686)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation$GrpcFuture.setException(AbstractRetryingOperation.java:119)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.setException(AbstractRetryingOperation.java:271)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onError(AbstractRetryingOperation.java:222)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onClose(AbstractRetryingOperation.java:187)
	at com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(ChannelPool.java:210)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$UnAuthResponseListener.onClose(RefreshingOAuth2CredentialsInterceptor.java:85)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:475)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:557)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:478)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:590)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: ABORTED: ReadModifyWrite failed: too many concurrent modifications.
	at io.grpc.Status.asRuntimeException(Status.java:517)
	... 19 more`

**Comment by vankofalcon** [comment]
my client flush interval is 1000

**Comment by sduskis** [comment]
`StatusRuntimeException` represents a server-side problem.  `too many concurrent modifications` seems to indicate that the server is saying that you're updating the same rowkey with too many concurrent requests.  `AtomicIncrementRequest` / HBase `Increment` / BIgtable `ReadModifyWrite`s don't require flushing, but rather the requests are sent immediately.

This problem is likely to be cause by the keys you're using then the client itself.  If you need to increment that quickly, you'll have to do some client-side caching and sending fewer `Increment` requests on the same key.

**Comment by vankofalcon** [comment]
I'm a little confused. The bigtable docs say that a single node can handle 10,000 QPS and 10 MB/s on random reads and writes. I don't see other limits. Can you please share knowledge about what kind of limits I can hit (like this one if you do lots of increments)?

**Comment by sduskis** [comment]
I do apologize for the confusing Cloud Bigtable documentation around about performance.  It's certainly a pain point for Cloud Bigtable customers.  It's proven difficult to cover all of the caveats adequately.

This github project deals with AsyncBigtable client-side issues, so I'll ask that you ask the question to a wider forum.  The [google-cloud-discuss group](https://groups.google.com/forum/#!forum/google-cloud-bigtable-discuss) is a good way to get more information about general Cloud Bigtable questions, and will have a wider audience of experts to answer your question.  

Please see the ["Getting Support" page in the Cloud Bigtable docs](https://cloud.google.com/bigtable/docs/support/getting-support) for information on how get support for this systemic issue.

**Comment by sduskis** [comment]
It's definitely worth pursing a more general discussion, but I'll give you two core concepts that mah help:

1. Cloud Bigtable does not do well with "hot keys".  If you update a single row with high write QPS to a single row. 

2. Cloud Bigtable is slower on Increment (aka ReadModifyWrite) than regular mutations.  General QPS will be significantly lower than if you do straight Reads or Writes.  ReadModifyWrite also is much less tolerant of the "hot key" problem.

The experts on the group can inform you better than I could.

**Comment by vankofalcon** [comment]
Thanks Solomon, you were right for the hot row. The performance is much better now. Thank you for the links and the help!
