### ISSUE TITLE
bigtable-hbase-2.x-hadoop-1.9.0 and JDK 11 issue

### ISSUE THREAD

**Issue by vankofalcon** [OpenTSDB/asyncbigtable#52]
It seems that java 11 is not supported. I get that error when I try to read data from bigtable:

`javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:629)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:511)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1060)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:211)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslEngine cannot be cast to class sun.security.ssl.SSLEngineImpl (com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslEngine is in unnamed module of loader 'app'; sun.security.ssl.SSLEngineImpl is in module java.base of loader 'bootstrap')
	at java.base/sun.security.ssl.SSLAlgorithmConstraints.<init>(SSLAlgorithmConstraints.java:132)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:267)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:237)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:625)
	... 26 more
} on channel 22.
Trailers: Metadata(bigtable-channel-id=22)"}
javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:629)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.internal.tcnative.SSL.readFromSSL(Native Method)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:511)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1060)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:211)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslEngine cannot be cast to class sun.security.ssl.SSLEngineImpl (com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslEngine is in unnamed module of loader 'app'; sun.security.ssl.SSLEngineImpl is in module java.base of loader 'bootstrap')
	at java.base/sun.security.ssl.SSLAlgorithmConstraints.<init>(SSLAlgorithmConstraints.java:132)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:267)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:141)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:237)
	at com.google.bigtable.repackaged.io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:625)
	... 26 more
`

I believe that this is because the bigtable driver uses old version of netty which does not support java 11. Am I right? Btw, the code runs fine on java 8.

**Comment by overthetop** [comment]
Hi there. Does anyone works on this?

**Comment by manolama** [comment]
You'll likely have to stick with JDK 8 for this. TSDB 3x is going to be JDK 9+ compatible and the Bigtable client is a module in that repo so try it out please.

**Comment by overthetop** [comment]
Hi @manolama Thank you for the response. What I'm looking for is a library that has the same interface as this one https://github.com/OpenTSDB/asynchbase but works with BigTable. That's why I'm using https://github.com/OpenTSDB/asyncbigtable with all the goodies. The reason for this is that we have migrated from HBase from BigTable. Maybe I've missed that, but I couldn't see here https://github.com/OpenTSDB/opentsdb/tree/3.0/storage/bigtable all the filters and stuff from the current repository. It looks like a different library to me. Do you guys have any plans to make the current repo work on java 11?

**Comment by manolama** [comment]
Hi @overthetop,
Yeah this would be your only option for backward(ish) compatibility with the AsyncHBase API. I'd start migrating to the native Bigtable client but in the meantime, could you build https://github.com/OpenTSDB/asyncbigtable/pull/56 with 1.8 and try running it under 11? See if that resolves the 11 issue for you please?

**Comment by vankofalcon** [comment]
@manolama Thank you! v 0.4.3 everything works as expected on jdk 11!
